"""ATT&CK Navigator layer export — generate shareable layer JSON from technique lists.

The Navigator layer format (v4.5) is the standard for sharing ATT&CK coverage maps.
Any analyst can drag-and-drop the output into https://mitre-attack.github.io/attack-navigator/
to get an instant visual heatmap.
"""

from __future__ import annotations

import json
from typing import Any

# Tactic phase → Navigator display order
_TACTIC_ORDER = [
    "reconnaissance",
    "resource-development",
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "defense-evasion",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]

# Score → color (red = confirmed, yellow = possible, green = detected)
_SCORE_COLORS = {
    1: "#ff6666",  # low confidence / sighted
    2: "#ffaa44",  # medium
    3: "#ffe766",  # high confidence
    4: "#8ec843",  # detected / hunting query exists
    5: "#28a745",  # fully covered (detection + validation)
}


def generate_navigator_layer(
    techniques: list[dict],
    layer_name: str = "Threat Research MCP — Mapped Techniques",
    layer_description: str = "",
    domain: str = "enterprise-attack",
    atomic_tests: dict[str, list[str]] | None = None,
) -> str:
    """Generate an ATT&CK Navigator layer from a list of mapped techniques.

    Args:
        techniques: List of dicts with keys: id, name, tactic, evidence (optional),
                    score (optional, 1-5).
        layer_name: Display name for the layer.
        layer_description: Optional description shown in Navigator.
        domain: ATT&CK domain — enterprise-attack, mobile-attack, or ics-attack.
        atomic_tests: Optional dict of technique_id → list of Atomic test IDs.

    Returns:
        JSON string in ATT&CK Navigator layer 4.5 format.
    """
    layer_techniques: list[dict[str, Any]] = []

    for tech in techniques:
        tid = tech.get("id", "").strip().upper()
        if not tid:
            continue

        tactic = tech.get("tactic", "").lower().replace("_", "-")
        score = int(tech.get("score", 3))
        score = max(1, min(5, score))
        color = tech.get("color") or _SCORE_COLORS.get(score, "#ffe766")

        evidence = tech.get("evidence", [])
        comment = "Evidence: " + ", ".join(evidence) if evidence else ""

        tests = (atomic_tests or {}).get(tid, [])
        if tests:
            comment += f"\nAtomic Tests: {', '.join(tests)}"

        entry: dict[str, Any] = {
            "techniqueID": tid,
            "tactic": tactic or None,
            "color": color,
            "comment": comment.strip(),
            "enabled": True,
            "score": score,
            "metadata": [],
            "links": [],
            "showSubtechniques": "." in tid,
        }
        # Remove None tactic — Navigator infers it
        if entry["tactic"] is None:
            del entry["tactic"]

        layer_techniques.append(entry)

    layer: dict[str, Any] = {
        "name": layer_name,
        "versions": {
            "attack": "14",
            "navigator": "4.9",
            "layer": "4.5",
        },
        "domain": domain,
        "description": layer_description
        or f"Generated by threat-research-mcp from {len(techniques)} mapped technique(s).",
        "filters": {
            "platforms": [
                "Windows",
                "macOS",
                "Linux",
                "Office 365",
                "Azure AD",
                "AWS",
                "GCP",
                "Azure",
                "Containers",
            ]
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
            "showAggregateScores": False,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": layer_techniques,
        "gradient": {
            "colors": ["#ff6666", "#ffe766", "#8ec843"],
            "minValue": 1,
            "maxValue": 5,
        },
        "legendItems": [
            {"label": "Sighted (low confidence)", "color": "#ff6666"},
            {"label": "Medium confidence", "color": "#ffaa44"},
            {"label": "High confidence", "color": "#ffe766"},
            {"label": "Hunt query available", "color": "#8ec843"},
            {"label": "Fully covered", "color": "#28a745"},
        ],
        "metadata": [],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }

    return json.dumps(layer, indent=2)


def navigator_layer_from_map_attack(map_attack_json: str, **kwargs) -> str:
    """Build a Navigator layer directly from map_attack() JSON output.

    Techniques with more evidence keywords get a higher score (up to 4).
    """
    try:
        result = json.loads(map_attack_json)
    except json.JSONDecodeError as exc:
        return json.dumps({"error": f"Invalid JSON: {exc}"})

    raw_techniques = result.get("techniques", [])
    enriched = []
    for tech in raw_techniques:
        evidence = tech.get("evidence", [])
        score = min(4, 1 + len(evidence))
        enriched.append(
            {
                "id": tech["id"],
                "name": tech["name"],
                "tactic": tech["tactic"],
                "evidence": evidence,
                "score": score,
            }
        )

    return generate_navigator_layer(enriched, **kwargs)
